/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Adam
 */
public class AddACoupon extends javax.swing.JFrame {

    /**
     * Creates new form AddACoupon
     */
    
    private Point mouseClickPoint;
    Booking booking;
    
    public AddACoupon(Booking booking) {
        this.booking = booking;
        initComponents();
        draggingFunction();
        setBackground(new Color(0,0,0,0));
    }
    
    private void draggingFunction() {
        
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            mouseClickPoint = e.getPoint();
        }

    });
    addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            Point newPoint = e.getLocationOnScreen();
            newPoint.translate(-mouseClickPoint.x, -mouseClickPoint.y);
            setLocation(newPoint);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        couponCodeTextField = new javax.swing.JTextField();
        errorCode = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 28, 20, 20));

        confirmButton.setBorderPainted(false);
        confirmButton.setContentAreaFilled(false);
        confirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 392, 380, 80));

        couponCodeTextField.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        couponCodeTextField.setForeground(new java.awt.Color(255, 255, 255));
        couponCodeTextField.setBorder(null);
        couponCodeTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        couponCodeTextField.setOpaque(false);
        getContentPane().add(couponCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 292, 450, 50));

        errorCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        errorCode.setForeground(new java.awt.Color(255, 0, 0));
        errorCode.setText("Invalid coupon code !");
        getContentPane().add(errorCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 180, 30));
        errorCode.setVisible(false);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/coupon.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseClicked
        boolean isValid = false;
        Coupon currentCoupon = null;
        for(int i= 0 ; i<MovieProject.allcoupon.numberofcoupon ; i++)
        {
            if(couponCodeTextField.getText().equals(MovieProject.allcoupon.coupon_list.get(i).getName())){
                isValid = true;
                currentCoupon = MovieProject.allcoupon.coupon_list.get(i);
            }
            
        }
        
        if (isValid){
            //double rate = 1 - (currentCoupon.getReduction()/100);
            MovieProject.bookpop.setDiscountRate((double) currentCoupon.getReduction()/100);
            this.dispose();
        }else{
            errorCode.setVisible(true);
        }
    }//GEN-LAST:event_confirmButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField couponCodeTextField;
    private javax.swing.JLabel errorCode;
    // End of variables declaration//GEN-END:variables
}
