/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/**
 *
 * @author Adam
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    
    private Point mouseClickPoint;
    
    private Movie movie;
    private Cinema cinemaSelected;
    
    private int childrenTicket = 0;
    private int adultTicket = 0;
    private int seniorTicket = 0;
    private double childrenPrice = 0.00;
    private double adultPrice = 0.00;
    private double seniorPrice = 0.00;
    private double discountRate = 0.00;
    private double discount = 0.00;
    private double vatRate = 0.055;
    private double vat =  0.00;
    private double subtotal = 0.00;
    private double total = 0.00;
    
    
    public Booking(Movie movie) {
        this.movie = movie;
        initComponents();
        updateLabels();
        draggingFunction();
        setBackground(new Color(0,0,0,0));
    }
    
    private void draggingFunction() {
        
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            mouseClickPoint = e.getPoint();
        }

    });
    addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            Point newPoint = e.getLocationOnScreen();
            newPoint.translate(-mouseClickPoint.x, -mouseClickPoint.y);
            setLocation(newPoint);
        }
    });
    }
    
    public double getTotal(){
        return total;
    }
    
    public Movie getMovie()
    {
        return movie;
    }
    
    public Cinema getCinema()
    {
        return cinemaSelected;
    }
    
    public int getChildrenTicket()
    {
        return childrenTicket;
    }
    
    public int getAdultTicket()
    {
        return adultTicket;
    }
    
    public int getSeniorTicket()
    {
        return seniorTicket;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        childrenLabel = new javax.swing.JLabel();
        adultLabel = new javax.swing.JLabel();
        seniorLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        vatLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        upChildren = new javax.swing.JButton();
        downChildren = new javax.swing.JButton();
        upAdult = new javax.swing.JButton();
        downAdult = new javax.swing.JButton();
        upSenior = new javax.swing.JButton();
        downSenior = new javax.swing.JButton();
        close = new javax.swing.JButton();
        childrenPriceLabel = new javax.swing.JLabel();
        adultPriceLabel = new javax.swing.JLabel();
        seniorPriceLabel = new javax.swing.JLabel();
        CouponButton = new javax.swing.JButton();
        warn1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a diffusion date" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 350, 50));

        Cinema[] cinemas = Movie.getMovieCinema(movie);
        String[] cinemasNames = new String[cinemas.length+1];
        cinemasNames[0] = "Select the cinema";
        for (int i = 0; i<cinemas.length; i++){
            cinemasNames[i+1] = cinemas[i].getName();
        }
        jComboBox2.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>( cinemasNames ));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 350, 50));

        childrenLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        childrenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        childrenLabel.setText("0");
        getContentPane().add(childrenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 248, 30, 30));

        adultLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        adultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adultLabel.setText("0");
        getContentPane().add(adultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 337, 30, 30));

        seniorLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        seniorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seniorLabel.setText("0");
        getContentPane().add(seniorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 431, 30, 30));

        subtotalLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        subtotalLabel.setText("0.00");
        getContentPane().add(subtotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 243, 90, 30));

        discountLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        discountLabel.setText("0.00");
        getContentPane().add(discountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 305, 90, 30));

        vatLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        vatLabel.setText("0.00");
        getContentPane().add(vatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 367, 90, 30));

        totalLabel.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        totalLabel.setText("0.00");
        getContentPane().add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 90, 30));

        buyButton.setBorderPainted(false);
        buyButton.setContentAreaFilled(false);
        buyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyButtonMouseClicked(evt);
            }
        });
        getContentPane().add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 330, 70));
        buyButton.setFocusPainted(false);

        cancelButton.setBorderPainted(false);
        cancelButton.setContentAreaFilled(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 330, 70));
        cancelButton.setFocusPainted(false);

        upChildren.setBorderPainted(false);
        upChildren.setContentAreaFilled(false);
        upChildren.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upChildren.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upChildrenMouseClicked(evt);
            }
        });
        getContentPane().add(upChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 235, 40, 20));
        upChildren.setFocusPainted(false);

        downChildren.setBorderPainted(false);
        downChildren.setContentAreaFilled(false);
        downChildren.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downChildren.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downChildrenMouseClicked(evt);
            }
        });
        downChildren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downChildrenActionPerformed(evt);
            }
        });
        getContentPane().add(downChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 272, 40, 20));
        downChildren.setFocusPainted(false);

        upAdult.setBorderPainted(false);
        upAdult.setContentAreaFilled(false);
        upAdult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upAdult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upAdultMouseClicked(evt);
            }
        });
        getContentPane().add(upAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 324, 40, 20));
        upAdult.setFocusPainted(false);

        downAdult.setBorderPainted(false);
        downAdult.setContentAreaFilled(false);
        downAdult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downAdult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downAdultMouseClicked(evt);
            }
        });
        getContentPane().add(downAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 361, 40, 20));
        downAdult.setFocusPainted(false);

        upSenior.setBorderPainted(false);
        upSenior.setContentAreaFilled(false);
        upSenior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upSenior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upSeniorMouseClicked(evt);
            }
        });
        getContentPane().add(upSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 417, 40, 20));
        upSenior.setFocusPainted(false);

        downSenior.setBorderPainted(false);
        downSenior.setContentAreaFilled(false);
        downSenior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downSenior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downSeniorMouseClicked(evt);
            }
        });
        getContentPane().add(downSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 454, 40, 20));
        downSenior.setFocusPainted(false);

        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 27, 20, 20));
        close.setFocusPainted(false);

        childrenPriceLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        childrenPriceLabel.setText("0.00");
        getContentPane().add(childrenPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 241, 90, 30));

        adultPriceLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        adultPriceLabel.setText("0.00");
        getContentPane().add(adultPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 329, 90, 30));

        seniorPriceLabel.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        seniorPriceLabel.setText("0.00");
        getContentPane().add(seniorPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 424, 90, 30));

        CouponButton.setToolTipText("Add a coupon code");
        CouponButton.setBorder(null);
        CouponButton.setContentAreaFilled(false);
        CouponButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CouponButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CouponButtonMouseClicked(evt);
            }
        });
        getContentPane().add(CouponButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 310, 20, 20));
        CouponButton.setFocusPainted(false);

        warn1.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        warn1.setForeground(new java.awt.Color(255, 0, 0));
        warn1.setText("* Please select a diffusion and the sits");
        getContentPane().add(warn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 400, -1));
        warn1.setVisible(false);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/booking2.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateLabels(){
        childrenLabel.setText(String.format("%d",childrenTicket));
        childrenPriceLabel.setText(String.format("%.2f",childrenPrice));
                
        adultLabel.setText(String.format("%d",adultTicket));
        adultPriceLabel.setText(String.format("%.2f",adultPrice));
        
        seniorLabel.setText(String.format("%d",seniorTicket));
        seniorPriceLabel.setText(String.format("%.2f",seniorPrice));
        
        subtotal = childrenTicket*childrenPrice + adultTicket*adultPrice + seniorTicket*seniorPrice;
        subtotalLabel.setText(String.format("%.2f",subtotal));
        
        discount = discountRate*subtotal;
        discountLabel.setText(String.format("%.2f",discount));
        
        vat = (subtotal-discount)*vatRate;
        vatLabel.setText(String.format("%.2f", vat));
        
        total = subtotal - discount + vat;
        if(ClientInfo.isConnected)
        {
            total *= 0.9;
        }
        if(ClientInfo.isPremium)
        {
            total *= 0.8;
        }
        totalLabel.setText(String.format("%.2f",total));
    }
    
    public void setDiscountRate(double rate){
        this.discountRate = rate;
        updateLabels();
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void downChildrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downChildrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downChildrenActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void upChildrenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upChildrenMouseClicked
        // TODO add your handling code here:
        childrenTicket += 1;
        updateLabels();
    }//GEN-LAST:event_upChildrenMouseClicked

    private void downChildrenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downChildrenMouseClicked
        // TODO add your handling code here:
        if (childrenTicket !=0 ){
            childrenTicket -= 1;
            updateLabels();
        }
    }//GEN-LAST:event_downChildrenMouseClicked

    private void upAdultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upAdultMouseClicked
        // TODO add your handling code here:
        adultTicket += 1;
        updateLabels();
    }//GEN-LAST:event_upAdultMouseClicked

    private void downAdultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downAdultMouseClicked
        // TODO add your handling code here:
        if (adultTicket !=0 ){
            adultTicket -= 1;
            updateLabels();
        }
    }//GEN-LAST:event_downAdultMouseClicked

    private void upSeniorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upSeniorMouseClicked
        // TODO add your handling code here:
        seniorTicket += 1;
        updateLabels();
    }//GEN-LAST:event_upSeniorMouseClicked

    private void downSeniorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downSeniorMouseClicked
        // TODO add your handling code here:
        if (seniorTicket !=0 ){
            seniorTicket -= 1;
            updateLabels();
        }
    }//GEN-LAST:event_downSeniorMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void buyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyButtonMouseClicked
        // TODO add your handling code here:
        if(total!=0 && jComboBox1.getSelectedIndex()!=0)
        {
            warn1.setVisible(false);
            MovieProject.bookpop.setVisible(false);
            new Checkout(total,true).setVisible(true);
        }
        else
        {
            warn1.setVisible(true);
        }
    }//GEN-LAST:event_buyButtonMouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED){
            if(jComboBox2.getSelectedIndex()!=0)
            {
            Cinema choosedCinema = Cinema.getCinema(evt.getItem().toString());
            
            childrenPrice = choosedCinema.getChildrenPrice();
            adultPrice = choosedCinema.getAdultPrice();
            seniorPrice = choosedCinema.getSeniorPrice();
            
            cinemaSelected = choosedCinema;
            ArrayList<Diffusion> list = AllDiffusion.getNextDiffusion(this.movie, choosedCinema);
            
            String diffusionlist[] = new String[list.size() + 1];
            
            diffusionlist[0] = "Select the diffusion";
            
            DateFormat dateFormat = new SimpleDateFormat("dd MMMMM yyyy");
            for(int i = 1; i< diffusionlist.length ; i++)
            {
               diffusionlist[i] = dateFormat.format(list.get(i-1).getDay()) + " - " + list.get(i-1).getHours().toString();
            }
             jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>( diffusionlist ));
            
            }
            else{
                childrenPrice = 0;
                adultPrice = 0;
                seniorPrice = 0;
            }
            updateLabels();
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void CouponButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CouponButtonMouseClicked
        // TODO add your handling code here:
        new AddACoupon(this).setVisible(true);
    }//GEN-LAST:event_CouponButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CouponButton;
    private javax.swing.JLabel adultLabel;
    private javax.swing.JLabel adultPriceLabel;
    private javax.swing.JButton buyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel childrenLabel;
    private javax.swing.JLabel childrenPriceLabel;
    private javax.swing.JButton close;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JButton downAdult;
    private javax.swing.JButton downChildren;
    private javax.swing.JButton downSenior;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel seniorLabel;
    private javax.swing.JLabel seniorPriceLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton upAdult;
    private javax.swing.JButton upChildren;
    private javax.swing.JButton upSenior;
    private javax.swing.JLabel vatLabel;
    private javax.swing.JLabel warn1;
    // End of variables declaration//GEN-END:variables
}
