/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Adam
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    private Point mouseClickPoint;
    private double price;
    private boolean isBooking;
    
    public Checkout(double price, boolean book) {
        this.price = price;
        this.isBooking = book;
        initComponents();
        setBackground(new Color(0,0,0,0));
        draggingFunction();
        priceLabel.setText("Pay £ " + String.format("%.2f",price));
    }
    
    private void draggingFunction() {
        
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            mouseClickPoint = e.getPoint();
        }

    });
    addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            Point newPoint = e.getLocationOnScreen();
            newPoint.translate(-mouseClickPoint.x, -mouseClickPoint.y);
            setLocation(newPoint);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        priceLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        CardNumberTextField = new javax.swing.JFormattedTextField();
        ExpiryDateTextField = new javax.swing.JFormattedTextField();
        CvcTextField = new javax.swing.JFormattedTextField();
        FormatError1 = new javax.swing.JLabel();
        FormatError2 = new javax.swing.JLabel();
        FormatError3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        priceLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 29)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(41, 41, 41));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Pay £ 0.00");
        priceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        priceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priceLabelMouseClicked(evt);
            }
        });
        getContentPane().add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 370, 70));

        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 28, 20, 20));
        closeButton.setFocusPainted(false);

        CardNumberTextField.setBorder(null);
        CardNumberTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            CardNumberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardNumberTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        CardNumberTextField.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        CardNumberTextField.setOpaque(false);
        CardNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CardNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 312, 450, 50));

        ExpiryDateTextField.setBorder(null);
        ExpiryDateTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            ExpiryDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ExpiryDateTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        ExpiryDateTextField.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        ExpiryDateTextField.setOpaque(false);
        ExpiryDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpiryDateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ExpiryDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 426, 190, 50));

        CvcTextField.setBorder(null);
        CvcTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            CvcTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CvcTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        CvcTextField.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        CvcTextField.setOpaque(false);
        getContentPane().add(CvcTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 210, 40));

        FormatError1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FormatError1.setForeground(new java.awt.Color(255, 51, 51));
        FormatError1.setText("*");
        getContentPane().add(FormatError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 315, -1, -1));
        FormatError1.setVisible(false);

        FormatError2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FormatError2.setForeground(new java.awt.Color(255, 51, 51));
        FormatError2.setText("*");
        getContentPane().add(FormatError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 427, -1, -1));
        FormatError2.setVisible(false);

        FormatError3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FormatError3.setForeground(new java.awt.Color(255, 51, 51));
        FormatError3.setText("*");
        getContentPane().add(FormatError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 427, -1, -1));
        FormatError3.setVisible(false);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/checkout.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void CardNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumberTextFieldActionPerformed

    private void ExpiryDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpiryDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpiryDateTextFieldActionPerformed

    private void priceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceLabelMouseClicked
        // TODO add your handling code here:
        boolean errorFormat = false;
        
        if (CardNumberTextField.getText().endsWith(" ")){
            errorFormat = true;
            FormatError1.setVisible(true);
        } else {FormatError1.setVisible(false);}
        
        if (ExpiryDateTextField.getText().endsWith(" ")){
            errorFormat = true;
            FormatError2.setVisible(true);
        }else {FormatError2.setVisible(false);}
        
        if (CvcTextField.getText().endsWith(" ")){
            errorFormat = true;
            FormatError3.setVisible(true);
        }else {FormatError3.setVisible(false);}
        
        
        if (!errorFormat){
            this.dispose();
            PaymentAccepted payment = new PaymentAccepted(isBooking);
            payment.setVisible(true);
            
        }
    }//GEN-LAST:event_priceLabelMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JFormattedTextField CardNumberTextField;
    private javax.swing.JFormattedTextField CvcTextField;
    private javax.swing.JFormattedTextField ExpiryDateTextField;
    private javax.swing.JLabel FormatError1;
    private javax.swing.JLabel FormatError2;
    private javax.swing.JLabel FormatError3;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
