/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Alexis
 */
public class OneMoviePanel extends javax.swing.JPanel {

    /**
     * Creates new form OneMoviePanel
     */
    private Movie movie;

    public OneMoviePanel(Movie movie) {
        this.movie = movie;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyButton = new javax.swing.JButton();
        authorLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1336, 490));
        setMinimumSize(new java.awt.Dimension(1336, 490));
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buyButton.setToolTipText("");
        buyButton.setBorder(null);
        buyButton.setBorderPainted(false);
        buyButton.setContentAreaFilled(false);
        buyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyButtonMouseClicked(evt);
            }
        });
        add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 340, 60));
        buyButton.setFocusPainted(false);

        authorLabel.setFont(new java.awt.Font("Comfortaa", 0, 20)); // NOI18N
        authorLabel.setText(movie.getAuthor());
        add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 401, 340, -1));

        dateLabel.setFont(new java.awt.Font("Comfortaa", 0, 20)); // NOI18N
        dateLabel.setText(movie.getReleaseDate().toString());
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 434, 290, 30));

        durationLabel.setFont(new java.awt.Font("Comfortaa", 0, 20)); // NOI18N
        durationLabel.setText(movie.getDuration()+" minutes");
        add(durationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 435, 300, -1));

        genreLabel.setFont(new java.awt.Font("Comfortaa", 0, 20)); // NOI18N
        String gendermovie = "";
        String[] genders = movie.getGender();
        for(int i=0;i<genders.length;i++)
        {

            gendermovie = gendermovie.concat(genders[i]);

            if(i != genders.length - 1)
            {
                gendermovie = gendermovie.concat(" / ");
            }

        }
        genreLabel.setText(gendermovie);
        add(genreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 401, 320, -1));

        nameLabel.setFont(new java.awt.Font("Comfortaa", 1, 40)); // NOI18N
        nameLabel.setText(movie.getName());
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 281, 840, 40));

        descLabel.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        descLabel.setText(movie.getDescription());
        descLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(descLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 306, 780, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/panelmovie.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(1336, 490));
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 1310, 250));
        try{

            URL url = new URL(movie.getImage());
            BufferedImage image = ImageIO.read(url);

            BufferedImage resized = resize(image, 250,1310);
            imageLabel.setIcon(new ImageIcon(resized));
        }catch(Exception e){
        }
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyButtonMouseClicked
        // TODO add your handling code here:
        if (MovieProject.bookpop!=null) {
            MovieProject.bookpop.dispose();
            MovieProject.bookpop = null;
        }
        MovieProject.bookpop = new Booking(movie);
        MovieProject.bookpop.setVisible(true);
    }//GEN-LAST:event_buyButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel background;
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    private BufferedImage resize(BufferedImage img, int height, int width) {
        if(img.getWidth()>=1320)
        {
            return img;
        }
        else{
            Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = resized.createGraphics();
            g2d.drawImage(tmp, 0, 0, null);
            g2d.dispose();
            return resized;
        }

    }
}
