/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adam
 */
public class PaymentAccepted extends javax.swing.JFrame {

    /**
     * Creates new form PaymentAccepted
     */
    private Point mouseClickPoint;
    private boolean isBooking;
    
    public PaymentAccepted(boolean book){
        this.isBooking = book;
        initComponents();
        setBackground(new Color(0,0,0,0));
        draggingFunction();
        
    }
    
    private void draggingFunction() {
        
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            mouseClickPoint = e.getPoint();
        }

    });
    addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            Point newPoint = e.getLocationOnScreen();
            newPoint.translate(-mouseClickPoint.x, -mouseClickPoint.y);
            setLocation(newPoint);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(550, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 28, 20, 20));
        jButton1.setFocusPainted(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/payment_accepted.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        MovieProject.mainapp.OneMoviePanel.setVisible(false);
        Date date = new Date(System.currentTimeMillis());
        if (isBooking)
        {
            
            Records.addToRecords(ClientInfo.ID, date, "Film : "+MovieProject.bookpop.getMovie().getName() + " - Cinema : " + MovieProject.bookpop.getCinema().getName() 
                    + " - Tickets : Childs: " +  MovieProject.bookpop.getChildrenTicket() 
                    + " ; Adult: " + MovieProject.bookpop.getAdultTicket()
                    + " ; Senior: " + MovieProject.bookpop.getSeniorTicket()
                    , MovieProject.bookpop.getTotal());

            if (MovieProject.bookpop != null)
            {
                MovieProject.bookpop.dispose();
                MovieProject.bookpop = null;  
            }
        }
        else{
            Records.addToRecords(ClientInfo.ID, date, "Premium Upgrade", 19.99);
            
            ClientInfo.isPremium = true;     
            String request = "UPDATE customerAccount SET premiumLevel = '1' WHERE client_id ='"+ClientInfo.ID+"';";
            try {
                
                Statement stat = SQLDatabase.dbLink.createStatement();
                int result = stat.executeUpdate(request);
                
                
                stat.close();
                
                App.updateUI();
            }
            catch(SQLException e) {
            }
        }
        
        App.updateUI();
        new PurchaseValid().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
