/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;



/**
 *
 * @author Alexis
 */
public class SignIn extends javax.swing.JFrame {
    
    /**
     * Creates new form SignIn
     */
    
    
    private Point mouseClickPoint;
    
    public SignIn() {
        initComponents();
        draggingFunction();
        setBackground(new Color(0,0,0,0));
    }
    
    private void draggingFunction() {
        
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            mouseClickPoint = e.getPoint();
        }

    });
    addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            Point newPoint = e.getLocationOnScreen();
            newPoint.translate(-mouseClickPoint.x, -mouseClickPoint.y);
            setLocation(newPoint);
        }
    });
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailError = new javax.swing.JLabel();
        invalidError = new javax.swing.JLabel();
        passwordError = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();
        signinButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        closeButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(550, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailError.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        emailError.setForeground(new java.awt.Color(255, 0, 0));
        emailError.setText("* No account found with this email");
        getContentPane().add(emailError, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 280, -1));
        emailError.setVisible(false);

        invalidError.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        invalidError.setForeground(new java.awt.Color(255, 0, 0));
        invalidError.setText("* Enter a valid email please");
        getContentPane().add(invalidError, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 280, -1));
        invalidError.setVisible(false);

        passwordError.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        passwordError.setForeground(new java.awt.Color(255, 0, 0));
        passwordError.setText("* Incorrect password");
        getContentPane().add(passwordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 345, 180, -1));
        passwordError.setVisible(false);

        joinButton.setBorder(null);
        joinButton.setContentAreaFilled(false);
        joinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        joinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinButtonMouseClicked(evt);
            }
        });
        getContentPane().add(joinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 140, 40));
        joinButton.setFocusPainted(false);

        signinButton.setBorder(null);
        signinButton.setContentAreaFilled(false);
        signinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinButtonMouseClicked(evt);
            }
        });
        getContentPane().add(signinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 475, 453, 95));
        signinButton.setFocusPainted(false);

        emailField.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        emailField.setForeground(new java.awt.Color(232, 232, 232));
        emailField.setBorder(null);
        emailField.setCaretColor(new java.awt.Color(232, 232, 232));
        emailField.setOpaque(false);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 281, 410, 50));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordField.setForeground(new java.awt.Color(232, 232, 232));
        passwordField.setToolTipText("");
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(232, 232, 232));
        passwordField.setOpaque(false);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 381, 410, 60));

        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 40, 40));
        closeButton.setFocusPainted(false);

        jCheckBox1.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jCheckBox1.setText("Stay connected");
        jCheckBox1.setToolTipText("");
        jCheckBox1.setContentAreaFilled(false);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 442, -1, -1));
        jCheckBox1.setFocusPainted(false);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/signin.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void joinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinButtonMouseClicked
        // TODO add your handling code here:
        MovieProject.popup = null;
        MovieProject.popup2 = null;
        MovieProject.popup = new SignUp();
        
        this.dispose();
        Point p = this.getLocation();
        Point a = new Point(p.x-100,p.y);
        MovieProject.popup.setLocation(a);
        MovieProject.popup.setVisible(true);
        
    }//GEN-LAST:event_joinButtonMouseClicked

    private void signinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseClicked
        
        passwordError.setVisible(false);
        emailError.setVisible(false);
        invalidError.setVisible(false);
        
        if(inputValidation.isValidEmail(emailField.getText()))
        {
            invalidError.setVisible(false);
            
            String request1 = "SELECT COUNT(*) FROM customerAccount WHERE email = '"+emailField.getText()+"';";
            String request2 = "SELECT COUNT(*) FROM customerAccount WHERE email = '"+emailField.getText()+"' AND password = '"+passwordField.getText()+"';";
            
            
            try {
                
                Statement stat = SQLDatabase.dbLink.createStatement();
                ResultSet result = stat.executeQuery(request1);
                result.next();
                if(result.getInt(1)==1)
                {
                    result.close();
                    
                    try {
                        ResultSet result2 = stat.executeQuery(request2);
                        result2.next();
                        if(result2.getInt(1)==1)
                        {
                            stat.close();
                            result2.close();
                            
                            ClientInfo.logIn(emailField.getText(), passwordField.getText());
                            
                            SignInValid signinvalid = new SignInValid();
                            
                            this.dispose();
                            Point p = this.getLocation();
                            MovieProject.mainapp.updateUI();
                            signinvalid.setLocation(p);
                            signinvalid.setVisible(true);
                            
                            if(jCheckBox1.isSelected())
                                AutomaticConnection.writeCookie(emailField.getText(), passwordField.getText());
  

                        }
                        else
                        {
                            passwordError.setVisible(true);
                            stat.close();
                            result2.close();
                        }
  
                    } catch(SQLException e){
                        if(MovieProject.debugMode) System.out.println("(Debug - ACube) An error as occured when the request 2 was send.");
                    }    
                }
                else
                {
                    emailError.setVisible(true);
                    stat.close();
                    result.close();
                }
                
                
            } catch(SQLException e){
                if(MovieProject.debugMode) System.out.println("(Debug - ACube) An error as occured when the request 1 was send.");
            }
            
            
            
        }
        else
        {
            invalidError.setVisible(true);
        }
    }//GEN-LAST:event_signinButtonMouseClicked

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if(inputValidation.isValidEmail(emailField.getText()))
        {
            invalidError.setVisible(false);
        }
        else
        {
            invalidError.setVisible(true);
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        MovieProject.signin = null;
    }//GEN-LAST:event_formWindowClosed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel emailError;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel invalidError;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel passwordError;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signinButton;
    // End of variables declaration//GEN-END:variables
}
