/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;

/**
 *
 * @author Alexis
 */
public class SignUp2 extends javax.swing.JFrame {

    /**
     * Creates new form SignUp2
     */
    
    protected String password;
    protected Date birthdate;
    
    private Point mouseClickPoint;
    
    public SignUp2() {
        initComponents();
        draggingFunction();
        setBackground(new Color(0,0,0,0));
    }
    
    private void draggingFunction() {
        
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            mouseClickPoint = e.getPoint();
        }

    });
    addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            Point newPoint = e.getLocationOnScreen();
            newPoint.translate(-mouseClickPoint.x, -mouseClickPoint.y);
            setLocation(newPoint);
        }
    });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordCheck2 = new javax.swing.JLabel();
        passwordCheck1 = new javax.swing.JLabel();
        passwordCheck3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordCField = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        closeButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordCheck2.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        passwordCheck2.setForeground(new java.awt.Color(255, 0, 0));
        passwordCheck2.setText("*");
        getContentPane().add(passwordCheck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 20, -1));
        passwordCheck2.setVisible(false);

        passwordCheck1.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        passwordCheck1.setForeground(new java.awt.Color(255, 0, 0));
        passwordCheck1.setText("* The two passwords must be identical. ");
        getContentPane().add(passwordCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 400, -1));
        passwordCheck1.setVisible(false);

        passwordCheck3.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        passwordCheck3.setForeground(new java.awt.Color(255, 0, 0));
        passwordCheck3.setText("*");
        getContentPane().add(passwordCheck3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 20, -1));
        passwordCheck3.setVisible(false);

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordField.setForeground(new java.awt.Color(232, 232, 232));
        passwordField.setToolTipText("");
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(232, 232, 232));
        passwordField.setOpaque(false);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 230, 50));

        passwordCField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordCField.setForeground(new java.awt.Color(232, 232, 232));
        passwordCField.setToolTipText("");
        passwordCField.setBorder(null);
        passwordCField.setCaretColor(new java.awt.Color(232, 232, 232));
        passwordCField.setOpaque(false);
        passwordCField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordCFieldFocusLost(evt);
            }
        });
        passwordCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordCField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 230, 50));

        jDateChooser1.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        jDateChooser1.setMaxSelectableDate(new java.util.Date(253370764902000L));
        jDateChooser1.setMaximumSize(new java.awt.Dimension(570, 40));
        jDateChooser1.setMinimumSize(new java.awt.Dimension(570, 40));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(570, 40));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 420, 570, 40));

        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 30, 40));
        closeButton.setFocusPainted(false);

        signupButton.setBorder(null);
        signupButton.setContentAreaFilled(false);
        signupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupButtonMouseClicked(evt);
            }
        });
        getContentPane().add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 310, 100));
        signupButton.setFocusPainted(false);

        previousButton.setBorder(null);
        previousButton.setContentAreaFilled(false);
        previousButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousButtonMouseClicked(evt);
            }
        });
        getContentPane().add(previousButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 180, 30));
        previousButton.setFocusPainted(false);

        emailField.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        emailField.setForeground(new java.awt.Color(232, 232, 232));
        emailField.setBorder(null);
        emailField.setCaretColor(new java.awt.Color(232, 232, 232));
        emailField.setOpaque(false);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 415, 560, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/signup2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void previousButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseClicked
        // TODO add your handling code here:
        Point p = MovieProject.popup2.getLocation();
        Point a = new Point(p.x,p.y);
        MovieProject.popup.setLocation(a);
        MovieProject.popup2.setVisible(false);
        MovieProject.popup.setVisible(true);
    }//GEN-LAST:event_previousButtonMouseClicked

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordCFieldActionPerformed

    private void signupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseClicked
        // TODO add your handling code here:
        
        boolean isValid = true;
        
        if(!inputValidation.isNotEmptyOrSpace(passwordField.getText()))
        {
            isValid = false;
        }

        if(!inputValidation.isNotEmptyOrSpace(passwordCField.getText()))
        {
            isValid = false;
        }
        
        if(!passwordField.getText().equals(passwordCField.getText()))
        {
            isValid = false;
        }
        
        if(isValid)
        {
            passwordCheck1.setVisible(false);
            passwordCheck2.setVisible(false);
            passwordCheck3.setVisible(false);
          
        }
        else
        {
            passwordCheck1.setVisible(true);
            passwordCheck2.setVisible(true);
            passwordCheck3.setVisible(true);
        }
        
        if(jDateChooser1.getDate()== null)
        {
            isValid = false;
        }
        
        
        if(isValid)
        { 
            passwordCheck1.setVisible(false);
            passwordCheck2.setVisible(false);
            passwordCheck3.setVisible(false);
            
            
            
            
            MovieProject.popup2.password = passwordField.getText();
            MovieProject.popup2.birthdate = new java.sql.Date(jDateChooser1.getDate().getTime());
            
            MovieProject.popup.dispose();
            MovieProject.popup2.dispose();
            
            ClientInfo.registerAccount(MovieProject.popup.firstname, MovieProject.popup.lastname, MovieProject.popup.email, MovieProject.popup2.password, MovieProject.popup2.birthdate);
            ClientInfo.logIn(MovieProject.popup.email, MovieProject.popup2.password);
            MovieProject.mainapp.updateUI();
            
            MovieProject.popup = null;
            MovieProject.popup2 = null;
        }
        
        
        
    }//GEN-LAST:event_signupButtonMouseClicked

    private void passwordCFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordCFieldFocusLost
        // TODO add your handling code here:
        if(passwordField.getText().equals(passwordCField.getText()))
        {
            passwordCheck1.setVisible(false);
            passwordCheck2.setVisible(false);
            passwordCheck3.setVisible(false);
        }
        else
        {
            
            passwordCheck1.setVisible(true);
            passwordCheck2.setVisible(true);
            passwordCheck3.setVisible(true);
        }
        
    }//GEN-LAST:event_passwordCFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField emailField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPasswordField passwordCField;
    private javax.swing.JLabel passwordCheck1;
    private javax.swing.JLabel passwordCheck2;
    private javax.swing.JLabel passwordCheck3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton signupButton;
    // End of variables declaration//GEN-END:variables
}
