/*
 * Copyright (C) 2021 Alexis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package movieproject;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;



/**
 *
 * @author Alexis
 */
public class SignUp extends javax.swing.JFrame {
    
    private Point mouseClickPoint;
    
    protected String firstname;
    protected String lastname;
    protected String email;
    
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        draggingFunction();
        setBackground(new Color(0,0,0,0));
    }
    
    private void draggingFunction() {
        
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            mouseClickPoint = e.getPoint();
        }

    });
    addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            Point newPoint = e.getLocationOnScreen();
            newPoint.translate(-mouseClickPoint.x, -mouseClickPoint.y);
            setLocation(newPoint);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkEmail = new javax.swing.JLabel();
        checkEmail2 = new javax.swing.JLabel();
        firstCheck = new javax.swing.JLabel();
        secondCheck = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        signinButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 650));
        setMinimumSize(new java.awt.Dimension(750, 650));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEmail.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        checkEmail.setForeground(new java.awt.Color(255, 0, 0));
        checkEmail.setText("* Please enter a valid email address");
        getContentPane().add(checkEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 375, -1, -1));
        checkEmail.setVisible(false);

        checkEmail2.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        checkEmail2.setForeground(new java.awt.Color(255, 0, 0));
        checkEmail2.setText("* This email address is already use");
        getContentPane().add(checkEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 375, -1, -1));
        checkEmail2.setVisible(false);

        firstCheck.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        firstCheck.setForeground(new java.awt.Color(255, 0, 0));
        firstCheck.setText("* Required");
        getContentPane().add(firstCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 240, 100, -1));
        firstCheck.setVisible(false);

        secondCheck.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        secondCheck.setForeground(new java.awt.Color(255, 0, 0));
        secondCheck.setText("* Required");
        getContentPane().add(secondCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 90, -1));
        secondCheck.setVisible(false);

        firstNameField.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(232, 232, 232));
        firstNameField.setBorder(null);
        firstNameField.setCaretColor(new java.awt.Color(232, 232, 232));
        firstNameField.setOpaque(false);
        firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusLost(evt);
            }
        });
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 281, 230, 50));

        lastNameField.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(232, 232, 232));
        lastNameField.setBorder(null);
        lastNameField.setCaretColor(new java.awt.Color(232, 232, 232));
        lastNameField.setOpaque(false);
        lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusLost(evt);
            }
        });
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 230, 50));

        emailField.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        emailField.setForeground(new java.awt.Color(232, 232, 232));
        emailField.setBorder(null);
        emailField.setCaretColor(new java.awt.Color(232, 232, 232));
        emailField.setOpaque(false);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 415, 560, 50));

        signinButton.setBorder(null);
        signinButton.setContentAreaFilled(false);
        signinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinButtonMouseClicked(evt);
            }
        });
        getContentPane().add(signinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 565, 120, 30));
        signinButton.setFocusPainted(false);

        nextButton.setBorder(null);
        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 310, 100));
        nextButton.setFocusPainted(false);

        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 30, 40));
        closeButton.setFocusPainted(false);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieproject/resources/signup.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_emailFieldActionPerformed

    private void signinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseClicked
        // TODO add your handling code here:
        
        if (MovieProject.signin == null)
        {
            MovieProject.signin = new SignIn();
            
        
        this.dispose();
        Point p = this.getLocation();
        Point a = new Point(p.x+100,p.y);
        MovieProject.signin.setLocation(a);
        MovieProject.signin.setVisible(true);
        }
    }//GEN-LAST:event_signinButtonMouseClicked
    
    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        // TODO add your handling code here:
        //SignUp2 signup2 = new SignUp2();
        
        boolean isValid = true;
        
        if(inputValidation.isValidEmail(emailField.getText()))
        {
            this.checkEmail.setVisible(false);
        }
        else
        {
            this.checkEmail.setVisible(true);
            isValid = false;
        }
        
        if(inputValidation.isNotEmptyOrSpace(firstNameField.getText()))
        {
            firstCheck.setVisible(false);
        }
        else
        {
            firstCheck.setVisible(true);
            isValid = false;
        }
        
        if(inputValidation.isNotEmptyOrSpace(lastNameField.getText()))
        {
            secondCheck.setVisible(false);
        }
        else
        {
            secondCheck.setVisible(true);
            isValid = false;
        }
        
        
        String request = "SELECT COUNT(*) FROM customerAccount WHERE email = '"+emailField.getText()+"';";
        
        try {
                
            Statement stat = SQLDatabase.dbLink.createStatement();
            ResultSet result = stat.executeQuery(request);
            result.next();
                if(result.getInt(1)>=1)
                {
                    isValid = false;
                    
                    checkEmail2.setVisible(true);
                    
                }
                else
                {
                    checkEmail2.setVisible(false);
                }
        }
        catch(SQLException e){
             if(MovieProject.debugMode) System.out.println("(Debug - ACube) An error as occured when the request from SignUp class was send.");
        }
        
        
        
        
        if(isValid)
        {
            if(MovieProject.popup2 == null)
            {
                    
                MovieProject.popup2 = new SignUp2();
                MovieProject.popup.setVisible(false);
                Point p = MovieProject.popup.getLocation();
                Point a = new Point(p.x,p.y);
                MovieProject.popup2.setLocation(a);
                MovieProject.popup2.setVisible(true);
            }
            else
            {
                Point p = MovieProject.popup.getLocation();
                Point a = new Point(p.x,p.y);
                MovieProject.popup2.setLocation(a);
                MovieProject.popup.setVisible(false);
                MovieProject.popup2.setVisible(true);
            }
            
            email = emailField.getText();
            firstname = firstNameField.getText();
            lastname = lastNameField.getText();
        }
        
    }//GEN-LAST:event_nextButtonMouseClicked

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if(inputValidation.isValidEmail(emailField.getText()))
        {
            checkEmail.setVisible(false);
        }
        else
        {
            checkEmail.setVisible(true);
        }
        
    }//GEN-LAST:event_emailFieldFocusLost

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
        // TODO add your handling code here:
        
        if(inputValidation.isNotEmptyOrSpace(firstNameField.getText()))
        {
            firstCheck.setVisible(false);
        }
        else
        {
            firstCheck.setVisible(true);
        }
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        // TODO add your handling code here:
        
        if(inputValidation.isNotEmptyOrSpace(lastNameField.getText()))
        {
            secondCheck.setVisible(false);
        }
        else
        {
            secondCheck.setVisible(true);;
        }
    }//GEN-LAST:event_lastNameFieldFocusLost

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel checkEmail;
    private javax.swing.JLabel checkEmail2;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel firstCheck;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel secondCheck;
    private javax.swing.JButton signinButton;
    // End of variables declaration//GEN-END:variables
}
